# -*- coding: utf-8 -*-
"""week4 ass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkFntvlt-xy5e0PRHAa6p_JGLmeh7wDp
"""



from google.colab import files
uploaded = files.upload() #this helps the user to upload the file to colab

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv('03_hospital_ops.csv')
df.head()
df.info()
df.isnull().any() #checking if there are any missing values in the file
df.duplicated().any() # checking if there are any duplicate values in the file

class Department:
    """
    Represents a single hospital ward/department
    Stores and processes data for one department
    """
    def __init__(self):
        self.df = None
        self.department_data = None

    def load_data(self, file_path):
        self.file_path = file_path
        try:#this helps in error handling
            temp_df = pd.read_csv(self.file_path)
        except FileNotFoundError:
            print(f"Error: File not found at '{self.file_path}'")
            return None
        except Exception as e:
            print(f"Error reading CSV file: {e}")
            return None

        try:
            # Check if 'department' column exists before setting as index
            if 'department' not in temp_df.columns:
                print("Error: 'department' column not found in the CSV file. Cannot set index.")
                return None
            self.df = temp_df.set_index('department')
        except Exception as e:
            print(f"Error setting 'department' as index: {e}")
            return None

        #converting the index column(departments) to lower case
        self.df.index = self.df.index.str.lower()
        #creating a list of departments(without repetitions) in the DataFrame
        departments = self.df.index.unique().tolist()
        # Displaying department options for user to choose from. Use of strip() to remove spaces
        print("Please choose a department from the list below")
        for i, dep in enumerate(departments, 1):
          print(f"{i}. {dep}")

        dep_name = input("Type the name of the department:").strip().lower()


        # Loops through the departments list and checks whether the input is in that list. If the input is not in the list, it prompts the user again for a correct input.
        while dep_name not in departments:
            print('Department not found. Please choose from the displayed options.')
            for i, dep in enumerate(departments, 1):
              print(f"{i}. {dep}")

            dep_name = input("Type the name of the department:").strip().lower()

        try:
            if dep_name in self.df.index:
                self.department_data = self.df.loc[dep_name]
                print(f"Data loaded successfully for {dep_name} department.")
                return self.department_data
            else:
                print(f"Error: Department '{dep_name}' not found in the dataset index after valid selection.")
                return None
        except KeyError:
            print(f"Error: Department '{dep_name}' not found in the dataset index.")
            return None
        except Exception as e:
            print(f"An unexpected error occurred while fetching department data: {e}")
            return None

class Hospital:
    """
    Represents a hospital with multiple departments
    Stores and processes data for multiple departments
    """
    def __init__(self):
        pass

    def calculate_kpis(self, data_df):
        if data_df is None or data_df.empty:
            print("Error: No data provided to calculate KPIs.")
            return None

        KPIS = ['average wait time', 'bed occupancy', 'scan utilization', 'number of departments']
        kpi_choice = input("Please choose a KPI from the list below:\n1. Average wait time \n2. Bed occupancy \n3. Scan utilization \n4. Number of departments \nType the name of KPI: ").lower()

        while kpi_choice not in KPIS:
            print('KPI not found. Please choose from the list provided.')
            kpi_choice = input("Please choose a KPI from the list below:\n1. Average wait time \n2. Bed occupancy \n3. Scan utilization \n4. Number of departments \nType the name of KPI: ").lower()

        try:
            if kpi_choice == 'average wait time':
                if 'avg_wait_min' in data_df.columns:
                    avg_wait_time = data_df['avg_wait_min'].mean()
                    return f'Average wait time = {avg_wait_time:.2f} minutes'
                else:
                    print("Error: 'avg_wait_min' column not found in the provided data.")
                    return None
            elif kpi_choice == 'bed occupancy':
                if 'beds_occupied' in data_df.columns and 'total_beds' in data_df.columns:
                    if (data_df['total_beds'] == 0).any():
                        print("Warning: Some 'total_beds' values are zero. These will be treated as NaN in occupancy calculation.")
                        daily_occupancy = (data_df['beds_occupied'] / data_df['total_beds'].replace(0, np.nan)) * 100
                    else:
                        daily_occupancy = (data_df['beds_occupied'] / data_df['total_beds']) * 100
                    avg_occupancy = daily_occupancy.mean()
                    return f'Average bed occupancy = {avg_occupancy:.2f}%'
                else:
                    print("Error: 'beds_occupied' or 'total_beds' column not found in the provided data.")
                    return None
            elif kpi_choice == 'scan utilization':
                if 'utilization_rate' in data_df.columns:
                    avg_utilization = data_df['utilization_rate'].mean()
                    return f'Scan utilization = {avg_utilization:.2f}'
                else:
                    print("Error: 'utilization_rate' column not found in the provided data.")
                    return None
            elif kpi_choice == 'number of departments':
                # This calculation assumes data_df represents a dataset where department info can be extracted.
                # If data_df is already a subset for a single department, this will likely be 1.
                if 'department' in data_df.columns:
                    num_departments = data_df['department'].nunique()
                elif data_df.index.name == 'department':
                    num_departments = data_df.index.nunique()
                else:
                    num_departments = 1 # Assume if no column/index named 'department', it's a single department's data
                return f'Number of unique departments in the provided data = {num_departments}'
            else:
                print("KPI not found. Please type the name of the KPI correctly as displayed.")
                return None
        except KeyError as ke:
            print(f"Error accessing column for KPI calculation: {ke}")
            return None
        except Exception as e:
            print(f"An unexpected error occurred during KPI calculation: {e}")
            return None


data = Department()
# Capture the returned DataFrame from load_data
department_df = data.load_data('03_hospital_ops.csv')

if department_df is not None:
    vicky = Hospital()
    # Pass the specific department_df to calculate_kpis
    kpi_result = vicky.calculate_kpis(department_df)
    if kpi_result:
        print(kpi_result)
    else:
        print("KPI calculation failed.")
else:
    print("Failed to load department data. KPI calculation aborted.")

#VISUALIZATION

#BAR CHART OF AVERAGE WAIT TIMES BY DEPARTMENT
avg_wait_times = df.groupby('department')['avg_wait_min'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=avg_wait_times.index, y=avg_wait_times.values, palette='viridis')
plt.title('Average Wait Time by Department')
plt.xlabel('Department')
plt.ylabel('Average Wait Time (minutes)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

#HEAT MAP OF DAILY OCCUPANCY RATES
df_reset = df.reset_index()
df_reset['date'] = pd.to_datetime(df_reset['date']).dt.date
daily_occupancy_df = df_reset.groupby(['department', 'date']).apply(lambda x: (x['beds_occupied'].sum() / x['total_beds'].sum()) * 100).reset_index(name='occupancy_rate')
occupancy_map = daily_occupancy_df.pivot(index='department', columns='date', values='occupancy_rate')
plt.figure(figsize=(15, 8))
sns.heatmap(occupancy_map, annot=True, fmt=".1f", cmap='YlGnBu', linewidths=.5, cbar_kws={'label': 'Occupancy Rate (%)'})
plt.title('Daily Bed Occupancy Rate per Department')
plt.xlabel('Date')
plt.ylabel('Department')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()


#LINE CHART FOR DAILY SCAN VOLUME
df_reset = df.reset_index()
df_reset['date'] = pd.to_datetime(df_reset['date'])
daily_scans = df_reset.groupby('date')['scans_done'].sum().reset_index()
plt.figure(figsize=(12, 7))
sns.lineplot(x='date', y='scans_done', data=daily_scans, marker='o')
plt.title('Daily Scan Volume Across All Departments')
plt.xlabel('Date')
plt.ylabel('Total Scans Done')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# VISUALIZATION DASHBOARD (MULTI-PANEL) AND SAVE AS .PNG

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Reset index and prepare data once
df_reset = df.reset_index()
df_reset['date'] = pd.to_datetime(df_reset['date'])

# -------------------------------
# Create figure with 3 subplots
# -------------------------------
fig, axes = plt.subplots(3, 1, figsize=(14, 18))

# -------------------------------
# 1. BAR CHART: Average Wait Time
# -------------------------------
avg_wait_times = (
    df.groupby('department')['avg_wait_min']
    .mean()
    .sort_values(ascending=False)
)

sns.barplot(
    x=avg_wait_times.index,
    y=avg_wait_times.values,
    ax=axes[0],
    palette='viridis'
)

axes[0].set_title('Average Wait Time by Department')
axes[0].set_xlabel('Department')
axes[0].set_ylabel('Average Wait Time (minutes)')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# -------------------------------
# 2. HEATMAP: Daily Occupancy
# -------------------------------
# Convert to date only (drop time)
df_reset['date_only'] = df_reset['date'].dt.date

daily_occupancy_df = (
    df_reset.groupby(['department', 'date_only'])[['beds_occupied', 'total_beds']]
    .sum()
)

daily_occupancy_df['occupancy_rate'] = (
    daily_occupancy_df['beds_occupied'] / daily_occupancy_df['total_beds']
) * 100

daily_occupancy_df = daily_occupancy_df.reset_index()

# Pivot with just date (no time)
occupancy_map = daily_occupancy_df.pivot(
    index='department',
    columns='date_only',
    values='occupancy_rate'
)

sns.heatmap(
    occupancy_map,
    ax=axes[1],
    annot=True,
    fmt=".1f",
    cmap='YlGnBu',
    linewidths=.5,
    cbar_kws={'label': 'Occupancy Rate (%)'}
)

axes[1].set_title('Daily Bed Occupancy Rate per Department')
axes[1].set_xlabel('Date')
axes[1].set_ylabel('Department')
axes[1].tick_params(axis='x', rotation=45)

# -------------------------------
# 3. LINE CHART: Daily Scan Volume
# -------------------------------
daily_scans = (
    df_reset.groupby('date')['scans_done']
    .sum()
    .reset_index()
)

sns.lineplot(
    x='date',
    y='scans_done',
    data=daily_scans,
    ax=axes[2],
    marker='o'
)

axes[2].set_title('Daily Scan Volume Across All Departments')
axes[2].set_xlabel('Date')
axes[2].set_ylabel('Total Scans Done')
axes[2].grid(True, linestyle='--', alpha=0.7)

# -------------------------------
# Final layout adjustments
# -------------------------------
plt.tight_layout()

# Save as PNG
plt.savefig('hospital_dashboard.png', dpi=300)

# Show dashboard
plt.show()

# EXTRA HEAT MAP OF OVERALL OCCUPANCY RATE PER DEPARTMENT

df_reset = df.reset_index()

# Compute occupancy safely (no apply)
department_occupancy = (
    df_reset.groupby('department')[['beds_occupied', 'total_beds']]
    .sum()
)

department_occupancy['occupancy_rate'] = (
    department_occupancy['beds_occupied'] / department_occupancy['total_beds']
) * 100

# Keep only occupancy rate
occupancy_map = department_occupancy[['occupancy_rate']]

plt.figure(figsize=(6, 6))
sns.heatmap(
    occupancy_map,
    annot=True,
    fmt=".1f",
    cmap='YlGnBu',
    linewidths=.5,
    cbar_kws={'label': 'Occupancy Rate (%)'}
)

plt.title('Overall Bed Occupancy Rate per Department')
plt.ylabel('Department')
plt.xlabel('')
plt.tight_layout()
plt.show()